-- MySQL Script generated by MySQL Workbench
-- Thu Feb 17 15:15:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `socialPet` DEFAULT CHARACTER SET utf8 ;
USE `socialPet` ;

-- -----------------------------------------------------
-- Table `mydb`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialPet`.`Accounts` (
  `idAccounts` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `passwort` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idAccounts`))
ENGINE = InnoDB;

--
-- Dumping data for table `Accounts`
--

LOCK TABLES `socialPet`.`Accounts` WRITE;
/*!40000 ALTER TABLE `lernapp_SWPra`.`profile` DISABLE KEYS */;
INSERT INTO `socialPet`.`Accounts` VALUES (1, 'Jannik', '1234', 'jannik@gmx.de');
/*!40000 ALTER TABLE `lernapp_SWPra`.`profile` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `mydb`.`beitraege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialPet`.`beitraege` (
  `idbeitraege` INT NOT NULL,
  `inhalt` VARCHAR(45) NULL,
  `datum` VARCHAR(45) NULL,
  `Accounts_id` INT NOT NULL,
  PRIMARY KEY (`idbeitraege`, `Accounts_id`),
  INDEX `fk_beitraege_Accounts_idx` (`Accounts_id` ASC) VISIBLE,
  CONSTRAINT `fk_beitraege_Accounts`
    FOREIGN KEY (`Accounts_id`)
    REFERENCES `socialPet`.`Accounts` (`idAccounts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
